name: cloud_music
description: Music player app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.1
  hive: ^2.2.3
  http: ^0.13.5
  dart_des: ^1.0.2
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  flutter_displaymode: ^0.4.1
  app_links: 2.2.2
  audio_service: ^0.18.7
  just_audio: ^0.9.30
  audio_session: ^0.1.11
  rxdart: ^0.27.7
  audio_video_progress_bar: ^0.11.0
  path_provider: ^2.0.11
  receive_sharing_intent: ^1.4.5
  uuid: ^3.0.7
  supabase: ^1.2.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.6
  material_design_icons_flutter: ^6.0.7096

flutter_icons:
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
